title: "HTB Writeups"
description: "Writeups for Hack The Box machines"
author: "DilipK5"
email: "you@example.com"
baseurl: ""  # Leave this empty if deploying to username.github.io
url: "https://dilipk5.github.io/HTB-blog"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

future: true  # Allows future-dated posts to be shown
show_excerpts: true

# Optional: If using tags/categories
collections:
  posts:
    output: true
