name: Sync HTB Writeups

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Blog Repo
        uses: actions/checkout@v3

      - name: Checkout HTB Labs Repo
        uses: actions/checkout@v3
        with:
          repository: dilipk5/HTB-Labs
          path: htb-labs

      - name: Copy and Format HTB Writeups
        run: |
          mkdir -p _posts
          rm -rf _posts/*
          for file in htb-labs/*.md; do
            filename=$(basename "$file" .md)
            today=$(date +%F)
            newfile="_posts/${today}-${filename}.md"
            # add frontmatter & copy file content
          done


      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-sync HTB writeups" || echo "No changes"
          git push
